export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";

export const GET_TODO_LOADING = "GET_TODO_LOADING";
export const GET_TODO_ERROR = "GET_TODO_ERROR";
export const GET_TODO_SUCCESS = "ADD_TODO_SUCCESS";

export const GET_SINGLE_TASK_LOADING = "GET_SINGLE_TASK_LOADING";
export const GET_SINGLE_TASK_ERROR = "GET_SINGLE_TASK_ERROR";
export const GET_SINGLE_TASK_SUCCESS = "GET_SINGLE_TASK_SUCCESS";